packages:
  - 'client'
  - 'server'
  - 'packages/api/*'
  - 'packages/*'

catalog:
  react: ^18.3.1
  react-dom: ^18.3.1
  '@types/react': ^18.3.3
  '@types/react-dom': ^18.3.0
  typescript: ^5.6.3
  vite: ^5.4.11
  express: ^4.21.1
  '@types/express': ^5.0.0
  '@types/node': ^22.9.0
  ts-node: ^10.9.2
  nodemon: ^3.1.7
  tsx: ^4.19.2
  mysql2: ^3.11.4
  knex: ^3.1.0
  cors: ^2.8.5
  tsup: ^8.3.5
  '@tanstack/react-query': ^5.60.6
  axios: 1.7.7
  '@types/cors': ^2.8.17
  zod: ^4.3.6
  '@vitejs/plugin-react': ^4.3.3
  formik: ^2.4.9
  leaflet: ^1.9.4
  react-leaflet: ^4.2.1
